# Sentry configuration

# Server-wide options for Sentry
Server:
 # If true Sentries will die like normal mobs, instead of being despawned. Player-type Sentry deaths will be announced in chat.
 DieLikePlayers: false
 # The amount of EXP sentries drop. Only works if Drops is turned on.
 ExpValue: 5
 # This is how often, in ticks, the Sentry performs his interal logic looking for targets, etc. Increasing this value may lighten
 # server load, but will decrease Sentries responsiveness and maximum rate of fire.
 LogicTicks: 5
 # Whether or not Sentries in bodyguard mode always deal damage regardless of other protection plugins.
 BodyguardsObeyProtection: true
 # Whether or not Sentries are immune to damage from entites on their ignore list. Immunity to damage also prevents retaliation.
 IgnoreListInvincibility: true
 
# Default stats for new Sentries
DefaultStats:
 Strength: 1
 Armour: 0
 NightVision: 16
 Range: 10
 VoiceRange: 0
 RespawnDelay: 10
 FollowDistance: 4
# More default stats...
DefaultValues:
 Speed: 1.0
 Health: 20.0
 ArrowRate: 2.0
 HealRate: 0.0
 Weight: 1.0     # used in knockback calculation
 
# Default options for new Sentries
DefaultOptions:
 DropInventory: false     # on death
 KillsDrop: true          # when killing others
 CriticalHits: true
 Invincible: false
 Retaliation: true
 FriendlyFire: false   # unused?
 MobsAttack: true
 IgnoreLOS: false
 
# Default texts for new Sentries. You can use <NPC> and <PLAYER> as placeholders.
DefaultTexts:
 Warning: "&c<NPC> says Halt! Come no closer!"
 Greeting: "&a<NPC> says Welcome, <PLAYER>"
 
# Default target list for new Sentries. 
DefaultTargets:
 #- "all:monsters"

# Default ignore list for new Sentries
DefaultIgnores:
 #- "owner"

UseCustomMessages: false
# Configurable messages used by all Sentries. You can use <NPC>, <PLAYER>, <ITEM>, and <AMOUNT> as 
# placeholders. Remove a message or set it to "" to prevent it from displaying at all.
GlobalTexts:
 Crit3: "&c*** You DISEMBOWEL <NPC> with your <ITEM> for <AMOUNT> damage"
 Crit2: "&6*** You MAIM <NPC> with your <ITEM> for <AMOUNT> damage"
 Crit1: "&e*** <NPC> sustains \"a mere flesh wound\" for <AMOUNT> damage"
 Hit: ""       # Message for all non-critcal hits, can get a bit spammy in chat, use with caution.
 Glance: "&f*** Your paltry blow does <AMOUNT> damage to <NPC>"
 Block: "&7*** <NPC> skillfully parries your attack!"
 Miss: "&7*** You MISSED! <NPC> thumbs their nose at you!"

# These are the percentage chancees of doing a certain damage to a Sentry if Criticals is turned on. 
# Whole numbers only. Set to 0 to disable a hit type.
UseCriticalHits: true 
HitChances:
 Crit3: 2
 Crit2: 4
 Crit1: 6
 Glance: 4
 Miss: 4
 
# List of other plugins that Sentry can integrate with to enable target selection to respect the 
# Teams/clan/faction/town/nation of players.  (ScoreboardTeams is the standard MC scoreboard.)
# To disable an option, remove or comment it out.
# NB Changes in these settings are not loaded by the /sentry reload command, only a server restart.
OtherPlugins:
  - Vault
  - Towny
  - Factions
  - SimpleClans
  - War
  - ScoreboardTeams 
  
# Settings to enable or disable the denizen integration features. These are enabled by default for
# backwards compatability, but only need to be active if you have Denizen scripts that are using them. 
# NB Changes in these settings are not loaded by the /sentry reload command, only a server restart.
DenizenIntegration:
  SentryHealthByDenizen: true
  # if you turn the setting above off (false), you will need to add the health trait to NPC's manually
  # for them to be able to take damage.
  NpcDeathTrigger: true
  NpcDeathTriggerOwner: true
  DieCommand: true
  LiveCommand: true


# Set true to customise the items used by each type of Sentry - configured below.
UseCustomWeapons: false 
# Use item names only. Remove an entry to disable that attack type. Any other item makes a Brawler.
AttackTypes:
 ARCHER: BOW
 PYRO1: REDSTONE_TORCH_ON
 PYRO2: TORCH
 PYRO3: BLAZE_ROD
 BOMBARDIER: EGG
 ICEMAGI: SNOW_BALL
 STORMCALLER1: PAPER
 STORMCALLER2: BOOK
 STORMCALLER3: BOOK_AND_QUILL
 # Note Witch Doctors need a potion equipped to know what to throw!
 WITCHDOCTOR: POTION
 WARLOCK1: ENDER_PEARL
 WARLOCK2: SKULL_ITEM
 CREEPER: SULPHUR

# The following items will ADD to the sentry's base armor. 
# Decimals are allowed but all minecraft damge is in integers. 
# You would need 2 items of 0.3 Armor buff to add 1 point of armor.
ArmorBuffs:
 #- IRON_HELMET 1.0
 #- DIAMOND_CHESTPLATE 4.0
 
# The following items will ADD to the sentry's base strength. 
StrengthBuffs:
 #- IRON_SWORD 1
 #- TORCH 5

# The following items will ADD to the sentry's base speed. 
SpeedBuffs:
 #- LEATHER_BOOTS 0.2
 #- IRON_BOOTS -0.1

# Apply potion effects on hit for various weapon types. Multiple effects allowed. 
# Use format: [item name] [potion name:duration in ticks:level] There are 20 ticks in a second. 
# Duration and Level are optional, default duration is 20, level is 1.
# Valid potion names: 
# speed, slow, fast_digging, slow_digging, increase_damage, heal, harm, jump, confusion, 
# regeneration, damage_resistance, fire_resistance, water_breathing, blindness, hunger, weakness, 
# poison, wither, health_boost, absorption, saturation, glowing, levitation, luck, unluck
WeaponEffects:
 - SNOW_BALL slow:20
 #- GOLD_SWORD poison:60:2 confusion
 
 
  
# The lists below control what items are equipped as armor. These should only be changed to disable 
# specific armors or add extended (i.e. Spout) items.
# If you are not changing the lists from the defaults, leave the "UseCustom..." values as false. 
 
UseCustomHelmets: false 
# If the value above is changed to true, the following items will be equipped as helmets, you must use the correct Material name.
Helmets:
   - PUMPKIN
   - JACK_O_LANTERN
   - LEATHER_HELMET
   - CHAINMAIL_HELMET
   - GOLD_HELMET
   - IRON_HELMET
   - DIAMOND_HELMET

UseCustomChestplates: false
# If the value above is changed to true, the following items will be equipped as chestplates, you must use the correct Material name.
Chestplates:
    - LEATHER_CHESTPLATE
    - CHAINMAIL_CHESTPLATE
    - GOLD_CHESTPLATE
    - IRON_CHESTPLATE
    - DIAMOND_CHESTPLATE

UseCustomLeggings: false
# If the value above is changed to true, the following items will be equipped as leggings, you must use the correct Material name.
Leggings:
    - LEATHER_LEGGINGS
    - CHAINMAIL_LEGGINGS
    - GOLD_LEGGINGS
    - IRON_LEGGINGS
    - DIAMOND_LEGGINGS
    
UseCustomBoots: false    
# If the value above is changed to true, the following items will be equipped as boots, you must use the correct Material name.
Boots:  
    - LEATHER_BOOTS
    - CHAINMAIL_BOOTS
    - GOLD_BOOTS
    - IRON_BOOTS
    - DIAMOND_BOOTS
    