#Sentry configuration

#Server-wide options for Sentry
Server:
 #If true Sentries will die like normal mobs, instead of being despawned. Player-type Sentry deaths will be announced in chat.
 DieLikePlayers: false
 #The amount of EXP sentries drop. Only works if Drops is turned on.
 ExpValue: 5

#Default stats for new Sentries
DefaultStats:
 Strength: 1
 Armor: 0
 Speed: 1.0
 Health: 20
 AttackRate: 2.0
 HealRate: 0.0
 NightVision: 16
 Range: 10
 WarningRange: 0
 Respawn: 10
 
#Default options for new Sentries
DefaultOptions:
 Drops: false
 Criticals: true
 Invincible: false
 Retaliate: true
 FriendlyFire: false
 
#Default texts for new Sentries. You can use <NPC> and <PLAYER> as placeholders.
DefaultTexts:
 Warning: <NPC> says Halt! Come no closer!
 Greeting: <NPC> says Welcome, <PLAYER>
 
#Default target list for new Sentries. 
DefaultTargets:
 #- entity:monster

 
#Default ignore list for new Sentries
DefaultIgnores:
 #- entity:owner

 
#Set the item used by each type of Sentry. Use item name or id #. 
#Remove an entry to disable that attack type. Any other item makes a Brawler.
AttackTypes:
 Archer: BOW
 Pyro1: REDSTONE_TORCH_ON
 Pyro2: TORCH
 Pyro3: BLAZE_ROD
 Bombardier: EGG
 IceMagi: SNOW_BALL
 StormCaller1: PAPER
 StormCaller2: BOOK
 #Note Witch Doctors need a potion equipped to know what to throw!
 WitchDoctor: POTION
 Warlock1: ENDER_PEARL

#The following items will ADD to the sentry's base armor. 
#Decimals are allowed but all minecraft damamge is in integers. 
#You would need 2 items of 0.3 Armor buff to add 1 point of armor.
ArmorBuffs:
 #- IRON_HELMET 1.0
 #- DIAMOND_CHESTPLATE 4.0
 
#The following items will ADD to the sentry's base strength. 
StrengthBuffs:
 #- IRON_SWORD 1
 #- TORCH 5

#The following items will ADD to the sentry's base speed. 
SpeedBuffs:
 #- LEATHER_BOOTS 0.2
 #- IRON_BOOTS -0.1

#Apply potion effects on hit for various weapon types. Multiple effects allowed. 
#Use format: [item name/id] [potion name/id:duration in ticks:level] There are 20 ticks in a second. 
#Duration and Level are optional, default duration is 20, level is 1.
#Valid potion names: 
#speed, slow, fast_digging, slow_digging, increase_damage, heal, harm, jump, confusion, 
#regeneration, damage_resistance, fire_resistance, water_breating, blindness, hunger, weakness, poison
WeaponEffects:
 - SNOW_BALL slow:20
 #- GOLD_SWORD poison:60:2 confusion
